- name: create ec2 and r53
  hosts: local
  connection: local
  gather_facts: false

  vars:
    ami_id: "ami-0220d79f3f480ecf5"
    sg_id: "sg-08aa3e7b6d2e04568"
    zone_id: "Z0130922213SF6HRWZW9U"
    domain_name: "daws85s.online"

    instances:
      - mongodb
      - redis
      - mysql
      - rabbitmq

  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_output

    # - name: print the ec-2 output
    #   ansible.builtin.debug:
    #     msg: "{{ ec2_output }}"









    # - name: print public_ip
    #   ansible.builtin.debug:
    #     msg: "{{ item.instances[0].public_ip_address }}"
    #   loop: "{{ ec2_output.results }}"

    # - name: print private_ip
    #   ansible.builtin.debug:
    #     msg: "{{ item.instances[0].private_ip_address }}"
    #   loop: "{{ ec2_output.results }}"

    - name: create route 53 record
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ item.item }}.{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      loop: "{{ ec2_output.results }}"


    - name: create route 53 record for frontend
      amazon.aws.route53:
        state: present
        zone: "{{ domain_name }}"
        record: "{{ domain_name }}"
        type: A
        ttl: 1
        value: "{{ item.instances[0].private_ip_address }}"
        overwrite: true
      when: item.item == "frontend"
      loop: "{{ ec2_output.results }}"
  
