[mongodb]
mongodb.daws85s.online

[redis]
redis.daws85s.online

[mysql]
mysql.daws85s.online

[rabbitmq]
rabbitmq.daws85s.online


[catalogue]
catalogue.daws85s.online

[cart]
cart.daws85s.online

[user]
user.daws85s.online


[shipping]
shipping.daws85s.online

[payment]
payment.daws85s.online

[frontend]
frontend.daws85s.online




[local]
localhost

[local:vars]
NAME=from inventory


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
















; COURSE=Ansible
; DURATION=10HRS
; TRAINER=Sivakumar

